---
title: "Class12"
author: "Matthew Tomaneng"
date: "5/10/2018"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Section 1
```{r}
#Load bio3d and download protein we're working with
#Already have it downloaded so just put it in the project enviornment
library(bio3d)
```
Next we will tranlate the file into something R can read
```{r}
hiv <- read.pdb("1hsg.pdb")
hiv
```
#Q1: What are the two non protein components
#A: Water and MK1 (ligand)

Section 1.2: Prepare initial protein and ligand input files
```{r}
#Trim data to components we can use isolated from each other
prot <- trim.pdb(hiv, "protein")
lig <- trim.pdb(hiv, "ligand")
#Now we are going to make these their own PDB files
write.pdb(prot, file="1hsg_protein.pdb")
write.pdb(lig, "1hsg_ligand.pdb")
```

Section 1.3: Using AutoDockTools to setup protein docking input
```{r}
#Most PDB files do not have charge and atom type so we need to add it using ADT

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

